table _Measures
	lineageTag: 6dd560a5-b5c9-4b14-94bc-58d1b69adb09

	measure PaS =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_NUMBER_OF_USERS] ),
			    Footfall[IS_GRAND_TOTAL] = 1,
			    Footfall[HOUR] = 25,
			    Footfall[HasValidSite] = TRUE()
			)
		formatString: #,0
		displayFolder: KPIs\Base
		lineageTag: fff3dce4-db9e-4175-8f3e-6e72c06ddeec

	measure OTS =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS] ),
			    Footfall[IS_GRAND_TOTAL] = 1,
			    Footfall[HOUR] = 25,
			    Footfall[HasValidSite] = TRUE()
			)
		formatString: #,0
		displayFolder: KPIs\Base
		lineageTag: 79b86f31-77d7-4674-81c4-2c970d29fae4
		dataCategory: Uncategorized

	measure 'Total Population' =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_USERS_2] ),
			    Footfall[IS_GRAND_TOTAL] = 1,
			    Footfall[HOUR] = 25,
			    Footfall[HasValidSite] = TRUE()
			)
		formatString: #,0
		displayFolder: KPIs\Base
		lineageTag: fa2e2818-1a2d-4fd7-a6bb-6a0269b9cd7a

	measure 'OTS by Movement' =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS] ),
			    Footfall[HOUR] = 25,
			    Footfall[VISITATION_MODALITY] = "All",
			    Footfall[IS_GRAND_TOTAL] = 0
			)
		displayFolder: KPIs\By movement
		lineageTag: 45805304-4e60-467f-91d1-88caab5b81aa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PaS by Movement' =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_NUMBER_OF_USERS] ),
			    Footfall[HOUR] = 25,
			    Footfall[VISITATION_MODALITY] = "All",
			    Footfall[IS_GRAND_TOTAL] = 0
			)
		displayFolder: KPIs\By movement
		lineageTag: 151686c3-9830-4f26-8f72-e8f5cca804f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Population by Movement' =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_USERS_2] ),
			    Footfall[HOUR] = 25,
			    Footfall[VISITATION_MODALITY] = "All",
			    Footfall[IS_GRAND_TOTAL] = 0
			)
		displayFolder: KPIs\By movement
		lineageTag: 5f53e214-68dc-46bc-b7ff-5db82c08bd40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTS by Visitation' =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS] ),
			    Footfall[HOUR] = 25,
			    Footfall[MOVEMENT_MODALITY] = "All",
			    Footfall[IS_GRAND_TOTAL] = 0
			)
		displayFolder: KPIs\By Visitation
		lineageTag: 1410cc1e-d91f-48e7-89bd-02251fec83c8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PaS by Visitation' =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_NUMBER_OF_USERS] ),
			    Footfall[HOUR] = 25,
			    Footfall[MOVEMENT_MODALITY] = "All",
			    Footfall[IS_GRAND_TOTAL] = 0
			)
		displayFolder: KPIs\By Visitation
		lineageTag: 078bc274-5508-4407-9f83-98c1e02c2a6b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Population by Visitation' =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_USERS_2] ),
			    Footfall[HOUR] = 25,
			    Footfall[MOVEMENT_MODALITY] = "All",
			    Footfall[IS_GRAND_TOTAL] = 0
			)
		displayFolder: KPIs\By Visitation
		lineageTag: 83e74fc8-0aa4-48fe-8069-5d9e2381a6f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Population (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_USERS_2] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25,
			    Footfall[HasValidSite] = TRUE () )
		formatString: #,0
		displayFolder: KPIs\By Hour
		lineageTag: fdbaddee-f7f9-4861-89ed-b7deba5ca6df

	measure 'PaS (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_USERS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25,
			    Footfall[HasValidSite] = TRUE () )
		formatString: #,0
		displayFolder: KPIs\By Hour
		lineageTag: 69a0f5ff-eb82-42a8-bec8-056496f4a26e

	measure 'OTS (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25,
			    Footfall[HasValidSite] = TRUE () )
		formatString: #,0
		displayFolder: KPIs\By Hour
		lineageTag: c8f94d63-c789-4916-988f-920de6bb2f16

	measure 'Age Audience (Hourly)' =
			
			SUMX (
			    FILTER ( Demographics_AgeLong, Demographics_AgeLong[MOVEMENT_MODALITY] = "All" ),
			    VAR _code = Demographics_AgeLong[CODE]
			    VAR _ym   = Demographics_AgeLong[YEAR_MONTH]
			    VAR _hr   = Demographics_AgeLong[HOUR]
			    VAR _pct  = DIVIDE ( Demographics_AgeLong[REACH_PCT], 100 )
			    RETURN
			        _pct *
			        CALCULATE (
			            SUM ( Footfall[EXTRAPOLATED_USERS_2] ),
			            Footfall[CODE]           = _code,
			            Footfall[YEAR_MONTH]     = _ym,
			            Footfall[HOUR]           = _hr,
			            Footfall[IS_GRAND_TOTAL] = 1,
			            Footfall[HasValidSite] = TRUE ()
			        )
			)
		formatString: #,0
		displayFolder: Age&Gender
		lineageTag: 459ed597-c6d9-46ed-b469-e907371fd71f

	measure 'Age Impressions (OTS)' =
			
			SUMX (
			    FILTER ( Demographics_AgeLong, Demographics_AgeLong[MOVEMENT_MODALITY] = "All" ),
			    VAR _code = Demographics_AgeLong[CODE]
			    VAR _ym   = Demographics_AgeLong[YEAR_MONTH]
			    VAR _hr   = Demographics_AgeLong[HOUR]
			    VAR _pct  = DIVIDE ( Demographics_AgeLong[REACH_PCT], 100 )
			    RETURN
			        _pct *
			        CALCULATE (
			            SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS_WEIGHTED] ),
			            Footfall[CODE]           = _code,
			            Footfall[YEAR_MONTH]     = _ym,
			            Footfall[HOUR]           = _hr,
			            Footfall[IS_GRAND_TOTAL] = 1
			        )
			)
		displayFolder: Age&Gender
		lineageTag: d5f2aefe-0bbe-4ef0-9227-52b1e969de5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Population (Inflation)' = DIVIDE ( [Total Population (Hourly)], [Total Population] )
		displayFolder: KPIs\Inflation
		lineageTag: 8f6756b9-de9d-44b9-b477-cc27295bf46e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PaS (Inflation)' = DIVIDE ( [PaS (Hourly)], [PaS] )
		displayFolder: KPIs\Inflation
		lineageTag: 859ed572-1028-4c31-aab1-0cad4f5183f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTS (Inflation)' = DIVIDE ( [OTS (Hourly)], [OTS] )
		formatString: 0.00
		displayFolder: KPIs\Inflation
		lineageTag: b6ccdc8b-99b2-4e7d-97dc-7712676069c5

	measure 'Header Title' =
			
			VAR NSites   = DISTINCTCOUNT ( Master_Sites[MM ID] )
			VAR MinDate  = CALCULATE ( MIN ( Footfall[DATE] ), Footfall[HasValidSite] = TRUE () )
			VAR MaxDate  = CALCULATE ( MAX ( Footfall[DATE] ), Footfall[HasValidSite] = TRUE () )
			VAR NoData   = ISBLANK ( MinDate )
			VAR Period =
			    SWITCH (
			        TRUE (),
			        NoData,                          "No period",
			        MinDate = MaxDate,               FORMAT ( MinDate, "D MMM YYYY" ),
			        YEAR ( MinDate ) = YEAR ( MaxDate ),
			            FORMAT ( MinDate, "D MMM" ) & " – " & FORMAT ( MaxDate, "D MMM YYYY" ),
			        FORMAT ( MinDate, "D MMM YYYY" ) & " – " & FORMAT ( MaxDate, "D MMM YYYY" )
			    )
			VAR SitesTxt = FORMAT ( NSites, "0" ) & " " & IF ( NSites = 1, "site", "sites" )
			RETURN
			    SitesTxt & " · " & Period
		displayFolder: Titles
		lineageTag: bb547881-aa04-4ec7-9831-ea4d67d39bfc

	measure 'Impressions Weighted (Daily)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS_WEIGHTED] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: Footfall QA\Impressions Weighted
		lineageTag: 42c53885-16f5-4b91-968e-388025ba22f6

	measure 'Impressions Weighted (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS_WEIGHTED] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: Footfall QA\Impressions Weighted
		lineageTag: db3373af-dc55-453c-8056-af39fde7d10f

	measure 'Impressions Weighted (Inflation)' =
			
			DIVIDE ( [Impressions Weighted (Hourly)], [Impressions Weighted (Daily)] )
		displayFolder: Footfall QA\Impressions Weighted
		lineageTag: 5c6066d5-d0e3-4685-8e65-db63e7996ee1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Impressions Weighted 2 (Daily)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS_WEIGHTED_2] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: Footfall QA\Impressions Weighted 2
		lineageTag: c64236c8-a5b2-4e24-9390-1ca34ea795db

	measure 'Impressions Weighted 2 (Inflation)' =
			
			DIVIDE ( [Impressions Weighted 2 (Hourly)], [Impressions Weighted 2 (Daily)] )
		displayFolder: Footfall QA\Impressions Weighted 2
		lineageTag: 90403f57-343c-417b-b6fa-8b2a853a8f29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Impressions Weighted 2 (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS_WEIGHTED_2] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: Footfall QA\Impressions Weighted 2
		lineageTag: e58c4ab2-7bcf-42f9-804b-a81a964f392e

	measure 'Ext Signals (Daily)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_SIGNALS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: Footfall QA\Ext Signals
		lineageTag: 03d1eeee-a8c3-4947-9265-9461c595f669

	measure 'Ext Signals (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_SIGNALS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: Footfall QA\Ext Signals
		lineageTag: 1c5354b3-a596-490d-b9c9-478dc5adafe3

	measure 'Ext Signals (Inflation)' =
			
			DIVIDE ( [Ext Signals (Hourly)], [Ext Signals (Daily)] )
		displayFolder: Footfall QA\Ext Signals
		lineageTag: 27910369-48ba-495a-92eb-8fafd071bf2b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ext Signals 2 (Daily)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_SIGNALS_2] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: Footfall QA\Ext Signal 2
		lineageTag: 248507cf-fc68-4dd7-80a8-f452014ce969

	measure 'Ext Signals 2 (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_SIGNALS_2] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: Footfall QA\Ext Signal 2
		lineageTag: b1674649-33fb-4c19-a189-ce525839cbb7

	measure 'Ext Signals 2 (Inflation)' =
			
			DIVIDE ( [Ext Signals 2 (Hourly)], [Ext Signals 2 (Daily)] )
		displayFolder: Footfall QA\Ext Signal 2
		lineageTag: 6e86724e-cbe9-4bf6-8ccb-24214ee5c671

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Eye Contacts (Daily)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_EYE_CONTACTS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: Footfall QA\Eyes Contacts
		lineageTag: 01980d29-4ba2-4ef9-b2e8-33b2e6579027

	measure 'Eye Contacts (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_EYE_CONTACTS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: Footfall QA\Eyes Contacts
		lineageTag: b02ec94f-75a6-4bba-89b3-f59e11391977

	measure 'Eye Contacts (Inflation)' =
			
			DIVIDE ( [Eye Contacts (Hourly)], [Eye Contacts (Daily)] )
		displayFolder: Footfall QA\Eyes Contacts
		lineageTag: 2a294606-6abe-415a-8992-1b9da159a734

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Eye Contacts Weighted (Daily)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_EYE_CONTACTS_WEIGHTED] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: Footfall QA\Eye Contacts Weighted
		lineageTag: 41447d8b-b58c-42f1-9b6f-da8c46e14a9a

	measure 'Eye Contacts Weighted (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_EYE_CONTACTS_WEIGHTED] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: Footfall QA\Eye Contacts Weighted
		lineageTag: 1183d6bd-606b-4abd-8332-c58da89f81b7

	measure 'Eye Contacts Weighted (Inflation)' =
			
			DIVIDE ( [Eye Contacts Weighted (Hourly)], [Eye Contacts Weighted (Daily)] )
		displayFolder: Footfall QA\Eye Contacts Weighted
		lineageTag: cfd5cdb2-1673-4ebc-b650-26a5ac398377

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Signals (Daily)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_SIGNALS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: Footfall QA\Signals
		lineageTag: 41e64c99-0a8c-445e-9bb9-cf4be15cb8e4

	measure 'Signals (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_SIGNALS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: Footfall QA\Signals
		lineageTag: 16643a4b-9b2b-4a8b-ba67-de8fbb0b1c87

	measure 'Signals (Inflation)' =
			
			DIVIDE ( [Signals (Hourly)], [Signals (Daily)] )
		displayFolder: Footfall QA\Signals
		lineageTag: 717f4497-1e3f-4c19-a42d-079ee241d3fd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Users (Daily)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_USERS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: Footfall QA\Users
		lineageTag: 23f803e8-6ea0-4352-bda2-29eb3bc031c5

	measure 'Users (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_USERS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: Footfall QA\Users
		lineageTag: 8cddcdbd-3141-44ec-b264-acef5d00ca4b

	measure 'Users (Inflation)' =
			
			DIVIDE ( [Users (Hourly)], [Users (Daily)] )
		displayFolder: Footfall QA\Users
		lineageTag: 43104164-49a7-4761-831e-411f6621a8f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dwell Time (Daily)' =
			
			CALCULATE ( AVERAGE ( Footfall[DWELL_TIME] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: Footfall QA\Dwell Time
		lineageTag: 077fe999-a575-4f47-b6f4-ec435a0c6dd9

	measure 'Dwell Time (Hourly avg)' =
			
			CALCULATE ( AVERAGE ( Footfall[DWELL_TIME] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: Footfall QA\Dwell Time
		lineageTag: 4d25e4d7-8344-4f44-b8f2-76a21065c229

	measure 'Dwell Time (Ratio)' =
			
			DIVIDE ( [Dwell Time (Hourly avg)], [Dwell Time (Daily)] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Footfall QA\Dwell Time
		lineageTag: 30246b75-a3d8-4ff0-9a05-2d683e4180b3

	measure 'Sites selected' = DISTINCTCOUNT(Footfall[CODE])
		formatString: 0
		displayFolder: Titles
		lineageTag: e6364c6d-d4d8-41c8-9fdc-86b4da501342

	measure 'Avg Daily Total Population' =
			
			AVERAGEX ( VALUES ( 'Calendar'[Date] ), [Total Population] )
		formatString: 0
		displayFolder: KPIs\AVG
		lineageTag: bd2b995e-9a84-4a7c-a76f-d6c383a9db57

	measure 'Avg Daily PaS' =
			
			AVERAGEX ( VALUES ( 'Calendar'[Date] ), [PaS] )
		formatString: 0
		displayFolder: KPIs\AVG
		lineageTag: e6b2cc0f-2171-4368-920e-f13bc3327e54

	measure 'Avg Daily OTS' =
			
			AVERAGEX ( VALUES ( 'Calendar'[Date] ), [OTS] )
		formatString: 0
		displayFolder: KPIs\AVG
		lineageTag: 4a776ea4-1cf0-40ab-9ccd-c68fb2d3bdc6

	measure 'Avg Hourly Total Population' =
			
			AVERAGEX ( VALUES ( 'Calendar'[Date] ), [Total Population (Hourly)])
		displayFolder: KPIs\AVG
		lineageTag: 5a4e0e63-b825-4603-aef8-6b2f6e47d856

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Hourly PaS' =
			
			AVERAGEX ( VALUES ( 'Calendar'[Date] ), [PaS (Hourly)])
		displayFolder: KPIs\AVG
		lineageTag: 8cec5dc7-38e1-4fbb-ab41-ca50f8a9d9f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Hourly OTS' =
			
			AVERAGEX ( VALUES ( 'Calendar'[Date] ), [OTS (Hourly)])
		displayFolder: KPIs\AVG
		lineageTag: 8c44ca3c-66f0-47b9-9991-5455dc916d07

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QA Daily' =
			
			SWITCH (
			    SELECTEDVALUE ( 'Dim Metric'[Metric] ),
			    "Dwell Time",             [Dwell Time (Daily)],
			    "Ext Signals",            [Ext Signals (Daily)],
			    "Ext Signals 2",          [Ext Signals 2 (Daily)],
			    "Eye Contacts",           [Eye Contacts (Daily)],
			    "Eye Contacts Weighted",  [Eye Contacts Weighted (Daily)],
			    "Impressions Weighted",   [Impressions Weighted (Daily)],
			    "Impressions Weighted 2", [Impressions Weighted 2 (Daily)],
			    "Signals",                [Signals (Daily)],
			    "EXTRAPOLATED_NUMBER_OF_USERS",        [PaS],
			    "EXTRAPOLATED_USERS_2",                [Total Population],
			    "EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS", [OTS],
			    "Users",                  [Users (Daily)]
			)
		displayFolder: Footfall QA
		lineageTag: 168466f6-07d5-4748-a8f3-8a901997e83c

		formatStringDefinition =
				IF (
				    SELECTEDVALUE ( 'Dim Metric'[Metric] ) = "Dwell Time",
				    "0.0%",
				    "#,##0"
				)

	measure 'QA Hourly' =
			
			SWITCH (
			    SELECTEDVALUE ( 'Dim Metric'[Metric] ),
			    "Dwell Time",             [Dwell Time (Hourly avg)],
			    "Ext Signals",            [Ext Signals (Hourly)],
			    "Ext Signals 2",          [Ext Signals 2 (Hourly)],
			    "Eye Contacts",           [Eye Contacts (Hourly)],
			    "Eye Contacts Weighted",  [Eye Contacts Weighted (Hourly)],
			    "Impressions Weighted",   [Impressions Weighted (Hourly)],
			    "Impressions Weighted 2", [Impressions Weighted 2 (Hourly)],
			    "Signals",                [Signals (Hourly)],
			    "EXTRAPOLATED_NUMBER_OF_USERS",        [PaS (Hourly)],
			    "EXTRAPOLATED_USERS_2",                [Total Population (Hourly)],
			    "EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS", [OTS (Hourly)],
			    "Users",                  [Users (Hourly)]
			)
		displayFolder: Footfall QA
		lineageTag: a08ce8fc-3041-4729-a0b6-83e1187d622e

		formatStringDefinition =
				IF (
				    SELECTEDVALUE ( 'Dim Metric'[Metric] ) = "Dwell Time",
				    "0.0%",
				    "#,##0"
				)

	measure 'QA Inflation' =
			
			SWITCH (
			    SELECTEDVALUE ( 'Dim Metric'[Metric] ),
			    "Dwell Time",             [Dwell Time (Ratio)],
			    "Ext Signals",            [Ext Signals (Inflation)],
			    "Ext Signals 2",          [Ext Signals 2 (Inflation)],
			    "Eye Contacts",           [Eye Contacts (Inflation)],
			    "Eye Contacts Weighted",  [Eye Contacts Weighted (Inflation)],
			    "Impressions Weighted",   [Impressions Weighted (Inflation)],
			    "Impressions Weighted 2", [Impressions Weighted 2 (Inflation)],
			    "Signals",                [Signals (Inflation)],
			    "EXTRAPOLATED_NUMBER_OF_USERS",        [PaS (Inflation)],
			    "EXTRAPOLATED_USERS_2",                [Total Population (Inflation)],
			    "EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS", [OTS (Inflation)],
			    "Users",                  [Users (Inflation)]
			)
		displayFolder: Footfall QA
		lineageTag: 463447a4-0685-44ff-82bd-22e34d7f37d5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visitation Audience' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_USERS_2] ),
			    Footfall[MOVEMENT_MODALITY] = "All",
			    Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: Modality
		lineageTag: 5924e282-4869-42b4-9fde-703272e8af4c

	measure 'Movement Audience' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_USERS_2] ),
			    Footfall[VISITATION_MODALITY] = "All",
			    Footfall[HOUR] <> 25 )
		displayFolder: Modality
		lineageTag: fef4d227-56f4-4c0d-abc2-2ac8819dfd05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Brand Affinity Index' = AVERAGE ( Brand_Affinity[BRAND_AFFINITY_INDEX] )
		displayFolder: Modality
		lineageTag: 898bba54-e4fd-49fb-b214-88a566d2c748

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Class Audience (Hourly)' =
			
			SUMX (
			    FILTER (
			        Demographics_ClassLong,
			        Demographics_ClassLong[MOVEMENT_MODALITY] = "All"
			            && Demographics_ClassLong[HasValidSite] = TRUE ()
			    ),
			    VAR _code = Demographics_ClassLong[CODE]
			    VAR _ym   = Demographics_ClassLong[YEAR_MONTH_KEY]
			    VAR _hr   = Demographics_ClassLong[HOUR]
			    RETURN
			        ( Demographics_ClassLong[REACH_PCT] / 100 )
			        * CALCULATE (
			            SUM ( Footfall[EXTRAPOLATED_USERS_2] ),
			            Footfall[CODE] = _code,
			            Footfall[YEAR_MONTH] = _ym,
			            Footfall[HOUR] = _hr,
			            Footfall[IS_GRAND_TOTAL] = 1,
			            Footfall[HasValidSite] = TRUE ()
			        )
			)
		formatString: #,0
		lineageTag: 53db95ee-a94a-4c8d-a009-67aa3fc03265

	measure 'Class %' =
			
			DIVIDE (
			    [Class Audience (Hourly)],
			    CALCULATE ( [Class Audience (Hourly)], REMOVEFILTERS ( Demographics_ClassLong[SEGMENT] ) )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 174514e5-9912-45ee-9ad7-307624207525

	measure 'Class Title' = "Audience by " & LOWER ( SELECTEDVALUE ( Demographics_ClassLong[BREAKDOWN], "class" ) )
		displayFolder: Titles
		lineageTag: e2472f7f-4e3c-4a6d-a4e0-0976b277fb94

	measure 'Site Header' =
			
			VAR SiteName = SELECTEDVALUE ( Master_Sites[Display Name] )
			VAR SiteID   = SELECTEDVALUE ( Master_Sites[MM ID] )
			RETURN
			    IF (
			        ISBLANK ( SiteName ),
			        "Multiple sites",
			        SiteName & " - MM ID " & SiteID
			    )
		displayFolder: Titles
		lineageTag: 27445238-20cc-42d9-9371-4af099f2895e

	measure 'Exposure Ratio' = DIVIDE( [OTS], [PaS] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Footfall QA
		lineageTag: b0700bd0-2797-4899-a865-57e5321da44b

	measure 'Total Screens' =
			
			CALCULATE(
			    DISTINCTCOUNT( Footfall[CODE] ),
			    Footfall[IS_GRAND_TOTAL] = 1,
			    Footfall[HOUR] = 25
			)
		formatString: 0
		displayFolder: Footfall QA
		lineageTag: d9851998-dd38-4840-9d19-b8dc0159d1ae

	measure 'Median Exposure (screen)' = MEDIANX( VALUES( Footfall[CODE] ), [Exposure Ratio] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Footfall QA
		lineageTag: 77182f5f-075d-4f37-a346-55312b554872

	measure 'P25 Exposure' = PERCENTILEX.INC( VALUES( Footfall[CODE] ), [Exposure Ratio], 0.25 )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Footfall QA
		lineageTag: 209b031c-008e-47d2-8ee9-43d31126be48

	measure 'P75 Exposure' = PERCENTILEX.INC( VALUES( Footfall[CODE] ), [Exposure Ratio], 0.75 )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Footfall QA
		lineageTag: b5da6c96-e399-411c-930d-5863b18b152f

	measure 'Male #' = CALCULATE ( [Age Audience (Hourly)], Demographics_AgeLong[GENDER] = "M" )
		formatString: #,0
		displayFolder: Age&Gender
		lineageTag: f089e020-ae88-469a-a714-5309b50c9197

	measure 'Female #' = CALCULATE ( [Age Audience (Hourly)], Demographics_AgeLong[GENDER] = "F" )
		formatString: #,0
		displayFolder: Age&Gender
		lineageTag: 1039ffec-ee87-4eef-a240-fed339d85c3c

	measure 'Under 18 #' = CALCULATE ( [Age Audience (Hourly)], Demographics_AgeLong[AGE_BRACKET] = "Under 18" )
		formatString: #,0
		displayFolder: Age&Gender
		lineageTag: 3a92c2ed-08d4-4299-88d7-f146f04f5c83

	measure '18-24 #' = CALCULATE ( [Age Audience (Hourly)], Demographics_AgeLong[AGE_BRACKET] = "18-24" )
		formatString: #,0
		displayFolder: Age&Gender
		lineageTag: cd512e12-0469-4b11-bacd-026f9523e4b8

	measure '25-34 #' = CALCULATE ( [Age Audience (Hourly)], Demographics_AgeLong[AGE_BRACKET] = "25-34" )
		formatString: #,0
		displayFolder: Age&Gender
		lineageTag: 722024eb-ad40-45c8-b386-4962d2908a7c

	measure '35-44 #' = ```
			CALCULATE ( [Age Audience (Hourly)], Demographics_AgeLong[AGE_BRACKET] = "35-44" )
			
			```
		formatString: #,0
		displayFolder: Age&Gender
		lineageTag: 6e63acfe-f499-4a00-afcb-aaa28a39146a

	measure '45-54 #' = ```
			CALCULATE ( [Age Audience (Hourly)], Demographics_AgeLong[AGE_BRACKET] = "45-54" )
			
			```
		formatString: #,0
		displayFolder: Age&Gender
		lineageTag: 871d1f65-6a41-4794-b1f8-c5a9969ac37a

	measure '55-64 #' = ```
			CALCULATE ( [Age Audience (Hourly)], Demographics_AgeLong[AGE_BRACKET] = "55-64" )
			
			```
		formatString: #,0
		displayFolder: Age&Gender
		lineageTag: 8caf33cb-673f-4f93-a8e8-86214296d373

	measure '65+ #' = CALCULATE ( [Age Audience (Hourly)], Demographics_AgeLong[AGE_BRACKET] = "65+" )
		formatString: #,0
		displayFolder: Age&Gender
		lineageTag: 68a901d2-4de6-471c-8ec0-741eb91b2c2b

	measure 'Male %' = DIVIDE ( [Male #], [Total Population (Hourly)] )
		displayFolder: Age&Gender
		lineageTag: 9a316a98-cc40-4e2f-b40c-039103202033

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Female %' = DIVIDE ( [Female #], [Total Population (Hourly)] )
		displayFolder: Age&Gender
		lineageTag: 756183be-3b8b-42a4-827a-a1ce58e859e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ranking Title' = "Top Screens"
		displayFolder: Titles
		lineageTag: 54e1e902-d7ce-4600-9e51-6c01197b568b

	measure 'Site Radius (m)' = ```
			
			   CALCULATE (
			       MAX ( Footfall[RADIUS] ),
			       Footfall[IS_GRAND_TOTAL] = 1,
			       Footfall[HOUR] = 25,
			       Footfall[HasValidSite] = TRUE ()
			   )
			```
		formatString: 0
		lineageTag: c3844f4e-5bef-4439-a17d-35105153599c

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCshJTE7NyM9JSS1Sio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

