table _Measures
	lineageTag: 6dd560a5-b5c9-4b14-94bc-58d1b69adb09

	measure PaS = CALCULATE( SUM( Footfall[EXTRAPOLATED_NUMBER_OF_USERS] ),  Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: 0
		displayFolder: KPIs\Base
		lineageTag: fff3dce4-db9e-4175-8f3e-6e72c06ddeec

	measure OTS = CALCULATE( SUM( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS] ), Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: 0
		displayFolder: KPIs\Base
		lineageTag: 79b86f31-77d7-4674-81c4-2c970d29fae4
		dataCategory: Uncategorized

	measure 'Total Population' = CALCULATE( SUM( Footfall[EXTRAPOLATED_USERS_2] ), Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: 0
		displayFolder: KPIs\Base
		lineageTag: fa2e2818-1a2d-4fd7-a6bb-6a0269b9cd7a

	measure 'OTS by Movement' =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS] ),
			    Footfall[HOUR] = 25,
			    Footfall[VISITATION_MODALITY] = "All",
			    Footfall[IS_GRAND_TOTAL] = 0
			)
		displayFolder: KPIs\By movement
		lineageTag: 45805304-4e60-467f-91d1-88caab5b81aa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PaS by Movement' =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_NUMBER_OF_USERS] ),
			    Footfall[HOUR] = 25,
			    Footfall[VISITATION_MODALITY] = "All",
			    Footfall[IS_GRAND_TOTAL] = 0
			)
		displayFolder: KPIs\By movement
		lineageTag: 151686c3-9830-4f26-8f72-e8f5cca804f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Population by Movement' =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_USERS_2] ),
			    Footfall[HOUR] = 25,
			    Footfall[VISITATION_MODALITY] = "All",
			    Footfall[IS_GRAND_TOTAL] = 0
			)
		displayFolder: KPIs\By movement
		lineageTag: 5f53e214-68dc-46bc-b7ff-5db82c08bd40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTS by Visitation' =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS] ),
			    Footfall[HOUR] = 25,
			    Footfall[MOVEMENT_MODALITY] = "All",
			    Footfall[IS_GRAND_TOTAL] = 0
			)
		displayFolder: KPIs\By Visitation
		lineageTag: 1410cc1e-d91f-48e7-89bd-02251fec83c8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PaS by Visitation' =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_NUMBER_OF_USERS] ),
			    Footfall[HOUR] = 25,
			    Footfall[MOVEMENT_MODALITY] = "All",
			    Footfall[IS_GRAND_TOTAL] = 0
			)
		displayFolder: KPIs\By Visitation
		lineageTag: 078bc274-5508-4407-9f83-98c1e02c2a6b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Population by Visitation' =
			
			CALCULATE(
			    SUM( Footfall[EXTRAPOLATED_USERS_2] ),
			    Footfall[HOUR] = 25,
			    Footfall[MOVEMENT_MODALITY] = "All",
			    Footfall[IS_GRAND_TOTAL] = 0
			)
		displayFolder: KPIs\By Visitation
		lineageTag: 83e74fc8-0aa4-48fe-8069-5d9e2381a6f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Population (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_USERS_2] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: 0
		displayFolder: KPIs\By Hour
		lineageTag: fdbaddee-f7f9-4861-89ed-b7deba5ca6df

	measure 'PaS (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_USERS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: 0
		displayFolder: KPIs\By Hour
		lineageTag: 69a0f5ff-eb82-42a8-bec8-056496f4a26e

	measure 'OTS (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: 0
		displayFolder: KPIs\By Hour
		lineageTag: c8f94d63-c789-4916-988f-920de6bb2f16

	measure 'Age Audience (Hourly)' =
			-- [Segments\Age]
			SUMX (
			    FILTER ( Demographics_AgeLong, Demographics_AgeLong[MOVEMENT_MODALITY] = "All" ),
			    VAR _code = Demographics_AgeLong[CODE]
			    VAR _ym   = Demographics_AgeLong[YEAR_MONTH]
			    VAR _hr   = Demographics_AgeLong[HOUR]
			    VAR _pct  = DIVIDE ( Demographics_AgeLong[REACH_PCT], 100 )
			    RETURN
			        _pct *
			        CALCULATE (
			            SUM ( Footfall[EXTRAPOLATED_USERS_2] ),
			            Footfall[CODE]           = _code,
			            Footfall[YEAR_MONTH]     = _ym,
			            Footfall[HOUR]           = _hr,
			            Footfall[IS_GRAND_TOTAL] = 1
			        )
			)
		displayFolder: Age&Gender
		lineageTag: 459ed597-c6d9-46ed-b469-e907371fd71f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Age Profile %' = ```
			-- [Segments\Age]
			DIVIDE ( [Age Audience (Hourly)], [Total Population (Hourly)] )
			
			```
		displayFolder: Age&Gender
		lineageTag: ef0a46b4-13a3-4e81-97fb-841f391a2b0c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Age Audience (Daily Unique)' =
			-- [Segments\Age]
			[Age Profile %] * [Total Population]
		displayFolder: Age&Gender
		lineageTag: 8cdb39fa-f2f5-4665-8614-8e60742ecc04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Age Impressions (OTS)' =
			-- [Segments\Age]
			SUMX (
			    FILTER ( Demographics_AgeLong, Demographics_AgeLong[MOVEMENT_MODALITY] = "All" ),
			    VAR _code = Demographics_AgeLong[CODE]
			    VAR _ym   = Demographics_AgeLong[YEAR_MONTH]
			    VAR _hr   = Demographics_AgeLong[HOUR]
			    VAR _pct  = DIVIDE ( Demographics_AgeLong[REACH_PCT], 100 )
			    RETURN
			        _pct *
			        CALCULATE (
			            SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS_WEIGHTED] ),
			            Footfall[CODE]           = _code,
			            Footfall[YEAR_MONTH]     = _ym,
			            Footfall[HOUR]           = _hr,
			            Footfall[IS_GRAND_TOTAL] = 1
			        )
			)
		displayFolder: Age&Gender
		lineageTag: d5f2aefe-0bbe-4ef0-9227-52b1e969de5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Age PaS (Daily Unique)' = [Age Profile %] * [PaS]                    -- [Segments\Age]
		displayFolder: Age&Gender
		lineageTag: 548a2df7-7893-4ee9-ba0e-91d2b6a08b51

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Class Audience (Hourly)' =
			-- [Segments\Class]
			SUMX (
			    FILTER ( Demographics_ClassLong, Demographics_ClassLong[MOVEMENT_MODALITY] = "All" ),
			    VAR _code = Demographics_ClassLong[CODE]
			    VAR _ym   = Demographics_ClassLong[YEAR_MONTH]
			    VAR _hr   = Demographics_ClassLong[HOUR]
			    VAR _pct  = DIVIDE ( Demographics_ClassLong[REACH_PCT], 100 )
			    RETURN
			        _pct *
			        CALCULATE (
			            SUM ( Footfall[EXTRAPOLATED_USERS_2] ),
			            Footfall[CODE]           = _code,
			            Footfall[YEAR_MONTH]     = _ym,
			            Footfall[HOUR]           = _hr,
			            Footfall[IS_GRAND_TOTAL] = 1
			        )
			)
		displayFolder: Professions
		lineageTag: b82e4c2d-b623-4ac9-9065-354524f02430

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Class Profile %' =
			-- [Segments\Class]
			DIVIDE ( [Class Audience (Hourly)], [Total Population (Hourly)] )
		displayFolder: Professions
		lineageTag: d8689c0b-14f7-4268-9b18-64f27a93fc34

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Class Audience (Daily Unique)' =
			-- [Segments\Class]
			[Class Profile %] * [Total Population]
		displayFolder: Professions
		lineageTag: b190f8ae-bf53-4504-85c2-125b6ffba077

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Class Impressions (OTS)' =
			-- [Segments\Class]
			SUMX (
			    FILTER ( Demographics_ClassLong, Demographics_ClassLong[MOVEMENT_MODALITY] = "All" ),
			    VAR _code = Demographics_ClassLong[CODE]
			    VAR _ym   = Demographics_ClassLong[YEAR_MONTH]
			    VAR _hr   = Demographics_ClassLong[HOUR]
			    VAR _pct  = DIVIDE ( Demographics_ClassLong[REACH_PCT], 100 )
			    RETURN
			        _pct *
			        CALCULATE (
			            SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS_WEIGHTED] ),
			            Footfall[CODE]           = _code,
			            Footfall[YEAR_MONTH]     = _ym,
			            Footfall[HOUR]           = _hr,
			            Footfall[IS_GRAND_TOTAL] = 1
			        )
			)
		displayFolder: Professions
		lineageTag: 572ff9c4-1fb5-48f9-baa6-787fb397fc82

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Class % Check (per cell)' =
			-- [Diagnostics]
			AVERAGEX (
			    SUMMARIZE (
			        FILTER ( Demographics_ClassLong, Demographics_ClassLong[MOVEMENT_MODALITY] = "All" ),
			        Demographics_ClassLong[CODE],
			        Demographics_ClassLong[YEAR_MONTH],
			        Demographics_ClassLong[HOUR],
			        Demographics_ClassLong[BREAKDOWN]
			    ),
			    CALCULATE ( SUM ( Demographics_ClassLong[REACH_PCT] ) )
			)
		displayFolder: Professions
		lineageTag: b46c218c-be2b-4daf-ae35-ad8fe0e4179d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ClassLong Rows' = COUNTROWS ( Demographics_ClassLong )
		formatString: 0
		lineageTag: 6cdf99b9-75fa-47a2-915d-33d7ebbe81aa

	measure 'Radii ClassLong' = DISTINCTCOUNT ( Demographics_ClassLong[RADIUS] )
		formatString: 0
		lineageTag: 3235f527-b9fb-4f93-a548-058dd171b6fc

	measure 'Radii AgeLong' = DISTINCTCOUNT ( Demographics_AgeLong[RADIUS] )
		formatString: 0
		lineageTag: cb4003b2-e5da-471f-b830-b5d17de80738

	measure 'Total Population (Inflation)' = DIVIDE ( [Total Population (Hourly)], [Total Population] )
		displayFolder: Inflation
		lineageTag: 8f6756b9-de9d-44b9-b477-cc27295bf46e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PaS (Inflation)' = DIVIDE ( [PaS (Hourly)], [PaS] )
		displayFolder: Inflation
		lineageTag: 859ed572-1028-4c31-aab1-0cad4f5183f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTS (Inflation)' = DIVIDE ( [OTS (Hourly)], [OTS] )
		formatString: 0.00
		displayFolder: Inflation
		lineageTag: b6ccdc8b-99b2-4e7d-97dc-7712676069c5

	measure 'Header Title' =
			
			VAR NSites  = DISTINCTCOUNT ( Master_Sites[MM ID] )
			VAR YM      = VALUES ( Footfall[YEAR_MONTH] )
			VAR Cnt     = COUNTROWS ( YM )
			VAR MinYM   = MINX ( YM, Footfall[YEAR_MONTH] )
			VAR MaxYM   = MAXX ( YM, Footfall[YEAR_MONTH] )
			VAR MinDate = DATE ( VALUE ( LEFT ( MinYM, 4 ) ), VALUE ( RIGHT ( MinYM, 2 ) ), 1 )
			VAR MaxDate = DATE ( VALUE ( LEFT ( MaxYM, 4 ) ), VALUE ( RIGHT ( MaxYM, 2 ) ), 1 )
			VAR Period =
			    SWITCH (
			        TRUE (),
			        Cnt = 0, "No period",
			        Cnt = 1, FORMAT ( MinDate, "MMMM YYYY" ),
			        FORMAT ( MinDate, "MMM YYYY" ) & " – " & FORMAT ( MaxDate, "MMM YYYY" )
			    )
			VAR SitesTxt = FORMAT ( NSites, "0" ) & " " & IF ( NSites = 1, "site", "sites" )
			RETURN
			    SitesTxt & " · " & Period
		displayFolder: Titles
		lineageTag: bb547881-aa04-4ec7-9831-ea4d67d39bfc

	measure 'Impressions Weighted (Daily)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS_WEIGHTED] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Impressions Weighted
		lineageTag: 42c53885-16f5-4b91-968e-388025ba22f6

	measure 'Impressions Weighted (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS_WEIGHTED] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Impressions Weighted
		lineageTag: db3373af-dc55-453c-8056-af39fde7d10f

	measure 'Impressions Weighted (Inflation)' =
			
			DIVIDE ( [Impressions Weighted (Hourly)], [Impressions Weighted (Daily)] )
		displayFolder: KPIs\By Hour\project01\Impressions Weighted
		lineageTag: 5c6066d5-d0e3-4685-8e65-db63e7996ee1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Impressions Weighted 2 (Daily)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS_WEIGHTED_2] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Impressions Weighted 2
		lineageTag: c64236c8-a5b2-4e24-9390-1ca34ea795db

	measure 'Impressions Weighted 2 (Inflation)' =
			
			DIVIDE ( [Impressions Weighted 2 (Hourly)], [Impressions Weighted 2 (Daily)] )
		displayFolder: KPIs\By Hour\project01\Impressions Weighted 2
		lineageTag: 90403f57-343c-417b-b6fa-8b2a853a8f29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Impressions Weighted 2 (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_EYE_CONTACTS_WEIGHTED_2] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Impressions Weighted 2
		lineageTag: e58c4ab2-7bcf-42f9-804b-a81a964f392e

	measure 'Ext Signals (Daily)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_SIGNALS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Ext Signals
		lineageTag: 03d1eeee-a8c3-4947-9265-9461c595f669

	measure 'Ext Signals (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_NUMBER_OF_SIGNALS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Ext Signals
		lineageTag: 1c5354b3-a596-490d-b9c9-478dc5adafe3

	measure 'Ext Signals (Inflation)' =
			
			DIVIDE ( [Ext Signals (Hourly)], [Ext Signals (Daily)] )
		displayFolder: KPIs\By Hour\project01\Ext Signals
		lineageTag: 27910369-48ba-495a-92eb-8fafd071bf2b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ext Signals 2 (Daily)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_SIGNALS_2] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Ext Signal 2
		lineageTag: 248507cf-fc68-4dd7-80a8-f452014ce969

	measure 'Ext Signals 2 (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[EXTRAPOLATED_SIGNALS_2] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Ext Signal 2
		lineageTag: b1674649-33fb-4c19-a189-ce525839cbb7

	measure 'Ext Signals 2 (Inflation)' =
			
			DIVIDE ( [Ext Signals 2 (Hourly)], [Ext Signals 2 (Daily)] )
		displayFolder: KPIs\By Hour\project01\Ext Signal 2
		lineageTag: 6e86724e-cbe9-4bf6-8ccb-24214ee5c671

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Eye Contacts (Daily)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_EYE_CONTACTS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Eyes Contacts
		lineageTag: 01980d29-4ba2-4ef9-b2e8-33b2e6579027

	measure 'Eye Contacts (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_EYE_CONTACTS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Eyes Contacts
		lineageTag: b02ec94f-75a6-4bba-89b3-f59e11391977

	measure 'Eye Contacts (Inflation)' =
			
			DIVIDE ( [Eye Contacts (Hourly)], [Eye Contacts (Daily)] )
		displayFolder: KPIs\By Hour\project01\Eyes Contacts
		lineageTag: 2a294606-6abe-415a-8992-1b9da159a734

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Eye Contacts Weighted (Daily)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_EYE_CONTACTS_WEIGHTED] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Eye Contacts Weighted
		lineageTag: 41447d8b-b58c-42f1-9b6f-da8c46e14a9a

	measure 'Eye Contacts Weighted (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_EYE_CONTACTS_WEIGHTED] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Eye Contacts Weighted
		lineageTag: 1183d6bd-606b-4abd-8332-c58da89f81b7

	measure 'Eye Contacts Weighted (Inflation)' =
			
			DIVIDE ( [Eye Contacts Weighted (Hourly)], [Eye Contacts Weighted (Daily)] )
		displayFolder: KPIs\By Hour\project01\Eye Contacts Weighted
		lineageTag: cfd5cdb2-1673-4ebc-b650-26a5ac398377

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Signals (Daily)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_SIGNALS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Signals
		lineageTag: 41e64c99-0a8c-445e-9bb9-cf4be15cb8e4

	measure 'Signals (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_SIGNALS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Signals
		lineageTag: 16643a4b-9b2b-4a8b-ba67-de8fbb0b1c87

	measure 'Signals (Inflation)' =
			
			DIVIDE ( [Signals (Hourly)], [Signals (Daily)] )
		displayFolder: KPIs\By Hour\project01\Signals
		lineageTag: 717f4497-1e3f-4c19-a42d-079ee241d3fd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Users (Daily)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_USERS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Users
		lineageTag: 23f803e8-6ea0-4352-bda2-29eb3bc031c5

	measure 'Users (Hourly)' =
			
			CALCULATE ( SUM ( Footfall[NUMBER_OF_USERS] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0
		displayFolder: KPIs\By Hour\project01\Users
		lineageTag: 8cddcdbd-3141-44ec-b264-acef5d00ca4b

	measure 'Users (Inflation)' =
			
			DIVIDE ( [Users (Hourly)], [Users (Daily)] )
		displayFolder: KPIs\By Hour\project01\Users
		lineageTag: 43104164-49a7-4761-831e-411f6621a8f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dwell Time (Daily)' =
			
			CALCULATE ( AVERAGE ( Footfall[DWELL_TIME] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] = 25 )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: KPIs\By Hour\project01\Dwell Time
		lineageTag: 077fe999-a575-4f47-b6f4-ec435a0c6dd9

	measure 'Dwell Time (Hourly avg)' =
			
			CALCULATE ( AVERAGE ( Footfall[DWELL_TIME] ),
			    Footfall[IS_GRAND_TOTAL] = 1, Footfall[HOUR] <> 25 )
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: KPIs\By Hour\project01\Dwell Time
		lineageTag: 4d25e4d7-8344-4f44-b8f2-76a21065c229

	measure 'Dwell Time (Ratio)' =
			
			DIVIDE ( [Dwell Time (Hourly avg)], [Dwell Time (Daily)] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPIs\By Hour\project01\Dwell Time
		lineageTag: 30246b75-a3d8-4ff0-9a05-2d683e4180b3

	measure 'Sites selected' = DISTINCTCOUNT(Footfall[CODE])
		formatString: 0
		displayFolder: Titles
		lineageTag: e6364c6d-d4d8-41c8-9fdc-86b4da501342

	measure 'Avg Daily Total Population' =
			
			AVERAGEX ( VALUES ( 'Calendar'[Date] ), [Total Population] )
		displayFolder: KPIs\AVG
		lineageTag: bd2b995e-9a84-4a7c-a76f-d6c383a9db57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Daily PaS' =
			
			AVERAGEX ( VALUES ( 'Calendar'[Date] ), [PaS] )
		displayFolder: KPIs\AVG
		lineageTag: e6b2cc0f-2171-4368-920e-f13bc3327e54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Daily OTS' =
			
			AVERAGEX ( VALUES ( 'Calendar'[Date] ), [OTS] )
		displayFolder: KPIs\AVG
		lineageTag: 4a776ea4-1cf0-40ab-9ccd-c68fb2d3bdc6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Hourly Total Population' =
			
			AVERAGEX ( VALUES ( 'Calendar'[Date] ), [Total Population (Hourly)])
		displayFolder: KPIs\AVG
		lineageTag: 5a4e0e63-b825-4603-aef8-6b2f6e47d856

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Hourly PaS' =
			
			AVERAGEX ( VALUES ( 'Calendar'[Date] ), [PaS (Hourly)])
		displayFolder: KPIs\AVG
		lineageTag: 8cec5dc7-38e1-4fbb-ab41-ca50f8a9d9f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Hourly OTS' =
			
			AVERAGEX ( VALUES ( 'Calendar'[Date] ), [OTS (Hourly)])
		displayFolder: KPIs\AVG
		lineageTag: 8c44ca3c-66f0-47b9-9991-5455dc916d07

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column1
		dataType: string
		isHidden
		lineageTag: cc97966a-36e7-4cce-8fb2-775c8aa75cb4
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCshJTE7NyM9JSS1Sio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

