table Demographics_AgeLong
	lineageTag: e0ce39ab-3c37-4f8a-9247-eb63cca8c8d5

	column CODE
		dataType: string
		lineageTag: 508d05bc-ddb3-4a60-9a2d-37290d285aed
		summarizeBy: none
		sourceColumn: CODE

		annotation SummarizationSetBy = Automatic

	column YEAR_MONTH
		dataType: string
		lineageTag: 5a1b05dd-b94e-4ee7-ad66-e4818d746f8a
		summarizeBy: none
		sourceColumn: YEAR_MONTH

		annotation SummarizationSetBy = Automatic

	column HOUR
		dataType: int64
		formatString: 0
		lineageTag: 0a1fc190-89ae-46d0-b66b-3497303f94b3
		summarizeBy: none
		sourceColumn: HOUR

		annotation SummarizationSetBy = Automatic

	column RADIUS
		dataType: int64
		formatString: 0
		lineageTag: a8cd61e4-bde9-4abd-8bef-70344c32e91c
		summarizeBy: sum
		sourceColumn: RADIUS

		annotation SummarizationSetBy = Automatic

	column MOVEMENT_MODALITY
		dataType: string
		lineageTag: c3d2a919-26ec-4cff-a035-654249a7fe5b
		summarizeBy: none
		sourceColumn: MOVEMENT_MODALITY

		annotation SummarizationSetBy = Automatic

	column AGE_BRACKET
		dataType: string
		lineageTag: 32fa4ff8-9802-4b4b-914f-84148d9e825a
		summarizeBy: none
		sourceColumn: AGE_BRACKET
		sortByColumn: AGE_SORT

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column GENDER
		dataType: string
		lineageTag: cd2d1987-54eb-463f-809e-d708e87bb1f8
		summarizeBy: none
		sourceColumn: GENDER

		annotation SummarizationSetBy = Automatic

	column REACH_PCT
		dataType: double
		lineageTag: 6233f414-cf21-4691-9fdd-69ba12f4db53
		summarizeBy: sum
		sourceColumn: REACH_PCT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SOURCE_FILE
		dataType: string
		lineageTag: ae5fd333-8e11-4bcb-9ec3-e289ee8e9a32
		summarizeBy: none
		sourceColumn: SOURCE_FILE

		annotation SummarizationSetBy = Automatic

	column AGE_SORT
		dataType: string
		lineageTag: 1fe744f0-c2e5-422b-9b9a-828c4e53ae22
		summarizeBy: none
		sourceColumn: AGE_SORT

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Gender Label' =
			
			SWITCH (
			    Demographics_AgeLong[GENDER],
			    "F", "Female",
			    "M", "Male",
			    Demographics_AgeLong[GENDER]
			)
		lineageTag: 0072257f-35a3-46ae-b448-d9919289b2a8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column HasValidSite = NOT ISBLANK ( RELATED ( Master_Sites[MM ID] ) )
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c874ac60-3d1a-4d10-8038-e18b73212278
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Demographics_AgeLong = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\brafa\Documents\data-analyst\MicroMedia\MicroMedia_Dashboard\data\demographics\age_long"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (6)", each #"Transform File (6)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (6)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (6)", Table.ColumnNames(#"Transform File (6)"(#"Sample File (6)"))),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Table Column1",{"Source.Name"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"CODE", type text}, {"YEAR_MONTH", type text}, {"MOVEMENT_MODALITY", type text}, {"RADIUS", Int64.Type}, {"HOUR", Int64.Type}, {"AGE_BRACKET", type text}, {"GENDER", type text}, {"REACH_PCT", type number}, {"SOURCE_FILE", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "AGE_SORT", each if [AGE_BRACKET] = "Under 18" then 0
				else if [AGE_BRACKET] = "18-24" then 1
				else if [AGE_BRACKET] = "25-34" then 2
				else if [AGE_BRACKET] = "35-44" then 3
				else if [AGE_BRACKET] = "45-54" then 4
				else if [AGE_BRACKET] = "55-64" then 5
				else 6)
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

