DEFINE
	VAR __DS0FilterTable = 
		FILTER(
			KEEPFILTERS(VALUES('Master_Sites'[MM ID])),
			AND('Master_Sites'[MM ID] IN {"50003"}, TRUE())
		)

	VAR __DS0FilterTable2 = 
		TREATAS({"Users"}, 'Metrics'[Group])

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'Master_Sites'[MM ID],
			'Master_Sites'[Display Name],
			__DS0FilterTable,
			__DS0FilterTable2,
			"Dwell_Time__Ratio_", '_Measures'[Dwell Time (Ratio)],
			"Dwell_Time__Daily_", '_Measures'[Dwell Time (Daily)],
			"Dwell_Time__Hourly_avg_", '_Measures'[Dwell Time (Hourly avg)]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(
			501,
			__DS0Core,
			[Dwell_Time__Ratio_],
			0,
			'Master_Sites'[MM ID],
			1,
			'Master_Sites'[Display Name],
			1
		)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[Dwell_Time__Ratio_] DESC, 'Master_Sites'[MM ID], 'Master_Sites'[Display Name]