EVALUATE
CALCULATETABLE (
    ADDCOLUMNS (
        VALUES ( Footfall[CODE] ),
        "TotalPop", CALCULATE ( SUM ( Footfall[EXTRAPOLATED_USERS_2] ), Footfall[IS_GRAND_TOTAL] = 1 ),
        "InMaster", IF ( NOT ISBLANK ( LOOKUPVALUE ( Master_Sites[MM ID], Master_Sites[MM ID], Footfall[CODE] ) ), "YES", "NO" )
    ),
    Footfall[HasValidSite] = FALSE ()
)
ORDER BY Footfall[CODE]