EVALUATE
TOPN (
    10,
    ADDCOLUMNS (
        CALCULATETABLE (
            VALUES ( Master_Sites[MM ID] ),
            Demographics_AgeLong[Gender Label] = "Female",
            Demographics_AgeLong[AGE_BRACKET] = "65+",
            dim_Hour[Hour] = 12,
            Calendar[YEAR_MONTH] = "2025-05"
        ),
        "Audience", [Age Audience (Hourly)]
    ),
    [Age Audience (Hourly)], DESC
)
ORDER BY [Age Audience (Hourly)] DESC